# Generated by Django 6.0.5 on 2026-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grave',
            name='status',
            field=models.CharField(choices=[('pending', 'Čeka odobrenje'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], default='approved', max_length=20),
        ),
    ]
