# Generated by Django 6.0.5 on 2026-05-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='comment_photos/'),
        ),
    ]
