# Generated by Django 6.0.5 on 2026-06-04 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0005_comment_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('location', 'Pogrešna lokacija'), ('wrong_cemetery', 'Pogrešno groblje'), ('duplicate', 'Duplikat'), ('photo', 'Problem sa fotografijom'), ('text', 'Problem sa tekstom/natpisom'), ('other', 'Ostalo')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Otvoreno'), ('resolved', 'Riješeno'), ('rejected', 'Odbijeno')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='graves.grave')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
