# Generated by Django 6.0.5 on 2026-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0006_problemreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemetery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
