# Generated by Django 6.0.5 on 2026-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0007_cemetery_latitude_cemetery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Nije poznato'), ('male', 'Muško'), ('female', 'Žensko')], default='', max_length=10, verbose_name='Spol'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons/%Y/%m/', verbose_name='Fotografija osobe'),
        ),
    ]
