# Generated by Django 6.0.5 on 2026-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0008_person_gender_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='grave_photos/originals/%Y/%m/'),
        ),
    ]
