# Generated by Django 6.0.5 on 2026-08-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0009_photo_image_original'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CemeteryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cemetery_photos/')),
                ('image_original', models.ImageField(blank=True, null=True, upload_to='cemetery_photos/originals/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Glavna fotografija')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cemetery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='graves.cemetery')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
