# Generated by Django 6.0.5 on 2026-08-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0010_cemeteryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemetery',
            name='cemetery_type',
            field=models.CharField(choices=[('muslimansko', 'Muslimansko'), ('katolicko', 'Katoličko'), ('pravoslavno', 'Pravoslavno'), ('hebrejsko', 'Hebrejsko'), ('partizansko', 'Partizansko'), ('stecci', 'Stećci'), ('vojno', 'Vojno'), ('gradsko', 'Gradsko'), ('seosko', 'Seosko'), ('porodicno', 'Porodično'), ('prirodno', 'Prirodno'), ('masovna_grobnica', 'Masovna grobnica'), ('spomen_groblje', 'Spomen-groblje'), ('nepoznato', 'Nepoznato'), ('ostalo', 'Ostalo')], default='nepoznato', max_length=30, verbose_name='Vrsta groblja'),
        ),
    ]
