# Generated by Django 6.0.5 on 2026-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0011_cemetery_cemetery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Glavna fotografija'),
        ),
    ]
