# Generated by Django 6.0.5 on 2026-08-16 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0012_photo_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='Dodao korisnik'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('pending', 'Čeka odobrenje'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], default='approved', max_length=20, verbose_name='Status'),
        ),
    ]
