# Generated by Django 6.0.5 on 2026-08-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0013_person_created_by_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_unknown',
            field=models.BooleanField(default=False, verbose_name='Nepoznata osoba'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
