# Generated by Django 6.0.5 on 2026-08-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0014_person_is_unknown_alter_person_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cemeteryphoto',
            name='status',
            field=models.CharField(choices=[('pending', 'Čeka odobrenje'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('pending', 'Čeka odobrenje'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], default='approved', max_length=20),
        ),
    ]
