# Generated by Django 6.0.5 on 2026-08-23 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0015_cemeteryphoto_status_photo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('first_name', 'Ime'), ('last_name', 'Prezime'), ('birth_year', 'Godina rođenja'), ('death_year', 'Godina smrti'), ('gender', 'Spol'), ('notes', 'Bilješke o osobi')], max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Čeka odobrenje'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='graves.person')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
