# Generated by Django 6.0.5 on 2026-09-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0016_personeditsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_original',
            field=models.ImageField(blank=True, null=True, upload_to='persons/originals/%Y/%m/', verbose_name='Arhivska fotografija osobe'),
        ),
    ]
