# Generated by Django 6.0.5 on 2026-09-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0017_person_photo_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentMacroType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Makro-tip spomenika',
                'verbose_name_plural': 'Makro-tipovi spomenika',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MonumentTradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Tradicija spomenika',
                'verbose_name_plural': 'Tradicije spomenika',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategorija')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Motiv / ornament',
                'verbose_name_plural': 'Motivi / ornamenti',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MonumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv')),
                ('level', models.CharField(choices=[('physical', 'Fizički tip'), ('morphological', 'Morfološki podtip'), ('detailed', 'Detaljni morfološki podtip')], default='physical', max_length=20, verbose_name='Nivo klasifikacije')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('identification_notes', models.TextField(blank=True, verbose_name='Kako prepoznati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='graves.monumenttype', verbose_name='Nadređeni tip')),
            ],
            options={
                'verbose_name': 'Tip spomenika',
                'verbose_name_plural': 'Tipovi spomenika',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
