# Generated by Django 6.0.5 on 2026-09-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0018_monumentmacrotype_monumenttradition_motif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grave',
            name='macro_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graves', to='graves.monumentmacrotype', verbose_name='Makro-tip'),
        ),
        migrations.AddField(
            model_name='grave',
            name='monument_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graves', to='graves.monumenttype', verbose_name='Tip spomenika'),
        ),
        migrations.AddField(
            model_name='grave',
            name='motifs',
            field=models.ManyToManyField(blank=True, related_name='graves', to='graves.motif', verbose_name='Motivi / ornamentika'),
        ),
        migrations.AddField(
            model_name='grave',
            name='tradition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graves', to='graves.monumenttradition', verbose_name='Tradicija / kontekst'),
        ),
    ]
