# Generated by Django 6.0.5 on 2026-09-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0019_grave_macro_type_grave_monument_type_grave_motifs_and_more'),
    ]

    operations = [
    ]
