# Generated by Django 6.0.5 on 2026-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0020_seed_monument_standard_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumenttype',
            name='level',
            field=models.CharField(choices=[('physical', 'Fizički tip'), ('morphological', 'Morfološki podtip'), ('detailed', 'Detaljni morfološki podtip'), ('functional', 'Funkcionalni tip'), ('local', 'Detaljni / lokalni tip'), ('reserve', 'Rezervni kod'), ('expert', 'Funkcionalna / stručna oznaka')], default='physical', max_length=20, verbose_name='Nivo klasifikacije'),
        ),
    ]
