# Generated by Django 6.0.5 on 2026-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0022_seed_monument_standard_v1_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteriorationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Stručni naziv')),
                ('group', models.CharField(choices=[('crack', 'Pukotine i deformacije'), ('detachment', 'Odvajanje materijala'), ('loss', 'Gubitak materijala'), ('discoloration', 'Promjene boje i naslage'), ('biological', 'Biološka kolonizacija')], max_length=20, verbose_name='Grupa')),
                ('admin_label', models.CharField(blank=True, max_length=200, verbose_name='Prikaz administratoru')),
                ('public_label', models.CharField(blank=True, max_length=200, verbose_name='Prikaz korisniku')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Pojava degradacije',
                'verbose_name_plural': 'Pojave degradacije',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MonumentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('public_label', models.CharField(blank=True, max_length=150, verbose_name='Naziv za javni unos')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Stanje spomenika',
                'verbose_name_plural': 'Stanja spomenika',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MonumentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=150, verbose_name='Naziv')),
                ('public_label', models.CharField(blank=True, max_length=150, verbose_name='Naziv za javni unos')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
            ],
            options={
                'verbose_name': 'Položaj spomenika',
                'verbose_name_plural': 'Položaji spomenika',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
