# Generated by Django 6.0.5 on 2026-09-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0023_deteriorationpattern_monumentcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grave',
            name='condition_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graves', to='graves.monumentcondition', verbose_name='Opće stanje spomenika'),
        ),
        migrations.AddField(
            model_name='grave',
            name='condition_notes',
            field=models.TextField(blank=True, help_text='Kratak opis vidljivog stanja, oštećenja i drugih zapažanja koja nisu dovoljno obuhvaćena šifrarnikom.', verbose_name='Opis stanja'),
        ),
        migrations.AddField(
            model_name='grave',
            name='deterioration_patterns',
            field=models.ManyToManyField(blank=True, related_name='graves', to='graves.deteriorationpattern', verbose_name='Uočene pojave degradacije'),
        ),
        migrations.AddField(
            model_name='grave',
            name='monument_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graves', to='graves.monumentposition', verbose_name='Položaj spomenika'),
        ),
    ]
