# Generated by Django 6.0.5 on 2026-10-09 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0025_seed_condition_standard_v1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cemetery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_cemeteries', to=settings.AUTH_USER_MODEL, verbose_name='Predložio korisnik'),
        ),
        migrations.AddField(
            model_name='cemetery',
            name='status',
            field=models.CharField(choices=[('pending', 'Čeka odobrenje'), ('approved', 'Odobreno'), ('rejected', 'Odbijeno')], db_index=True, default='approved', max_length=20, verbose_name='Status odobravanja'),
        ),
    ]
