"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv("/opt/wiki-greblje/.env", override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=(l(ohfm_6qq66098vz9dj(sck^nk=_b^+(22e3hw=*ql%*5@f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
    "172.30.137.192",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'corsheaders',
    'leaflet',
    'cemeteries',
    'graves.apps.GravesConfig',
    'photos',
    'accounts',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "graves.context_processors.pending_graves_count",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.name == "nt":
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": "wiki_groblje",
            "USER": "wiki_user",
            "PASSWORD": "HamuZUZU2026",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": "wiki_greblje",
            "USER": "wikiadmin",
            "PASSWORD": "HamuZUZU2026",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (43.9889, 18.1781),
    "DEFAULT_ZOOM": 17,
    "MIN_ZOOM": 3,
    "MAX_ZOOM": 22,
    "SCALE": "both",
    "ATTRIBUTION_PREFIX": "Wiki Greblje",
}

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES["default"] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
    )

    DATABASES["default"]["ENGINE"] = "django.contrib.gis.db.backends.postgis"


import os
if os.name != "nt":
    os.environ.setdefault("PROJ_LIB", "/usr/share/proj")
    os.environ.setdefault("PROJ_DATA", "/usr/share/proj")
    os.environ.setdefault("GDAL_DATA", "/usr/share/gdal")
    
if os.name == "nt":
    GDAL_LIBRARY_PATH = r"C:\Users\Administrator\AppData\Local\Programs\OSGeo4W\bin\gdal312.dll"
    GEOS_LIBRARY_PATH = r"C:\Users\Administrator\AppData\Local\Programs\OSGeo4W\bin\geos_c.dll"
    os.environ["PATH"] = r"C:\Users\Administrator\AppData\Local\Programs\OSGeo4W\bin;" + os.environ["PATH"]
    os.environ["GDAL_DATA"] = r"C:\Users\Administrator\AppData\Local\Programs\OSGeo4W\share\gdal"
    os.environ["PROJ_LIB"] = r"C:\Users\Administrator\AppData\Local\Programs\OSGeo4W\share\proj"
    os.environ["PROJ_DATA"] = r"C:\Users\Administrator\AppData\Local\Programs\OSGeo4W\share\proj"
